import type { Metadata } from "next";
import "./globals.css";
import ClientLogic from "./ClientLogic";
import ClientBody from "./ClientBody"; // 新增

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClientBody> {/* 替换 <body> 标签 */}
        <ClientLogic />
        {children}
      </ClientBody>
    </html>
  );
}