// lib/data.ts - 完整产品数据

export const initialProducts = [
  {
    id: '1',
    name: 'CRISPR-Cas9 Kit',
    description: 'Complete genome editing toolkit for precise DNA modifications',
    price: '$299',
    category: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop',
    showOnHomepage: true,
    showInGeneEditing: true,
    isReagent: false,
  },
  {
    id: '2',
    name: 'Polymerase Enzyme',
    description: 'High-fidelity DNA polymerase for PCR applications',
    price: '$189',
    category: 'reagent',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&h=300&fit=crop',
    showOnHomepage: false,
    showInGeneEditing: false,
    isReagent: true,
  },
  {
    id: '3',
    name: 'Gene Sequencing Kit',
    description: 'Next-generation sequencing preparation kit',
    price: '$450',
    category: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
    showOnHomepage: true,
    showInGeneEditing: false,
    isReagent: false,
  },
  {
    id: '4',
    name: 'RNA Extraction Kit',
    description: 'Ultra-pure RNA isolation for genetic material analysis from various samples',
    price: '$235',
    category: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    showOnHomepage: true,
    showInGeneEditing: false,
    isReagent: false,
  },
  {
    id: '5',
    name: 'TALEN Assembly Kit',
    description: 'Transcription activator-like effector nucleases',
    price: '$520',
    category: 'gene-editing',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&h=300&fit=crop',
    showOnHomepage: false,
    showInGeneEditing: true,
    isReagent: false,
  },
  {
    id: '6',
    name: 'ZFN Design Tool',
    description: 'Zinc finger nuclease design and validation',
    price: '$380',
    category: 'gene-editing',
    imageUrl: 'https://images.unsplash.com/photo-1518495978942-83cdb633d6d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    showOnHomepage: false,
    showInGeneEditing: true,
    isReagent: false,
  },
  {
    id: '7',
    name: 'Cell Culture Media',
    description: 'Complete media for mammalian cell culture',
    price: '$89',
    category: 'reagent',
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031d5ad?w=400&h=300&fit=crop',
    showOnHomepage: false,
    showInGeneEditing: false,
    isReagent: true,
  },
  {
    id: '8',
    name: 'Protein Purification Kit',
    description: 'Affinity purification for recombinant proteins',
    price: '$310',
    category: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=400&h=300&fit=crop',
    showOnHomepage: true,
    showInGeneEditing: false,
    isReagent: false,
  },
  {
    id: '9',
    name: 'CRISPR gRNA Design',
    description: 'Guide RNA design software with off-target analysis',
    price: '$650',
    category: 'gene-editing',
    imageUrl: 'https://images.unsplash.com/photo-1511376777868-611b54f68947?w=400&h=300&fit=crop',
    showOnHomepage: false,
    showInGeneEditing: true,
    isReagent: false,
  },
  {
    id: '10',
    name: 'Antibody Production Kit',
    description: 'Complete kit for monoclonal antibody production',
    price: '$420',
    category: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1582719471384-894e7c16f0d8?w=400&h=300&fit=crop',
    showOnHomepage: true,
    showInGeneEditing: false,
    isReagent: false,
  },
  {
    id: '11',
    name: 'Buffers & Solutions Pack',
    description: 'Essential laboratory buffers and chemical solutions',
    price: '$125',
    category: 'reagent',
    imageUrl: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=400&h=300&fit=crop',
    showOnHomepage: false,
    showInGeneEditing: false,
    isReagent: true,
  },
  {
    id: '12',
    name: 'Stem Cell Culture Kit',
    description: 'Complete kit for stem cell maintenance and differentiation',
    price: '$580',
    category: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&h=300&fit=crop',
    showOnHomepage: true,
    showInGeneEditing: false,
    isReagent: false,
  },
];

export const initialServices = [
  {
    id: 's1',
    name: 'Gene Synthesis',
    description: 'Custom gene synthesis and codon optimization services',
    showOnHomepage: true,
  },
  {
    id: 's2',
    name: 'CRISPR Design',
    description: 'Professional gRNA design and off-target analysis',
    showOnHomepage: true,
  },
  {
    id: 's3',
    name: 'Protein Expression',
    description: 'Recombinant protein expression and purification',
    showOnHomepage: false,
  },
  {
    id: 's4',
    name: 'Cell Line Development',
    description: 'Stable cell line development and validation',
    showOnHomepage: false,
  },
  {
    id: 's5',
    name: 'Sequencing Analysis',
    description: 'Next-generation sequencing data analysis',
    showOnHomepage: true,
  },
  {
    id: 's6',
    name: 'Bioinformatics Support',
    description: 'Custom bioinformatics pipeline development',
    showOnHomepage: false,
  },
];